### ISSUE TITLE
Bounty Board Integration

### ISSUE THREAD

**Issue by amaredeus** [BanklessDAO/discord-bots#12]
Pasting this here from discord chat

https://discord.com/channels/834499078434979890/834940559750725633/850804219539619860

Problem:
Bounties are distributed and not in a centralized location causing information distribution issues and making it challenging for users to get involved.

Solution:
Bounty board

Bounty definition
Single guild initiative(?)
-Title
-Description
-Guild
-Requestee(s)
-Bounty

Need:
bounty.bankless.community

Bounty board website (two examples of layout) - 2000 BANK
-List active bounties
-List completed and in-progress bounties
-reportability for analytics

bounty intake website(one example layout) - 1000 BANK
-bot integration and to post to a general channel in discord
-People self assign via the Discord bot (clicking thumbs up)

BOT work - 2000 BANK
-Function:
--discord:
---Take bounties with !bounty command
---Post to #bounty channel
---Intermittently repost bounties, date requested, summary, etc.
---Update the bounty board per people assigning (thumbs up... or whatever)
---Require people to be level 0 to self assign
---Needs to be able to take bank into escrow
----IF level 1:Pay 25% up front, 75% upon confirmation of the requestee liking the product.
----If level 0: no up front 100% upon completion.

Total Bounty: 6000 BANK

**Comment by amaredeus** [comment]
Bounty Board commands created
/bounty create new # create new bounty
/bounty create validate # validate bounty created from front end
/bounty list # list available bounties
/bounty claim # claim and open bounty

**Comment by amaredeus** [comment]
A round of discussions was held for bountyboard commands. A few important features what should be included in MVP of bountyboard:
 - post bounties in #bounties channel
 - assign/complete bounties based on emojis
 - add additional fields to bounty commands to support flow without frontend

**Comment by nonsensecodes** [comment]
As the current iteration of the Bounty command is complete, we'll close this issue. Excellent work, @amaredeus!
