### ISSUE TITLE
Username Spam Filter

### ISSUE THREAD

**Issue by nonsensecodes** [BanklessDAO/discord-bots#51]
[Above Average Joe asked](https://discord.com/channels/834499078434979890/850205786721746954/864524178518704140) if we would implement an autoban feature where DEGEN would recognize specific terms in a username and ban them if the terms exist there. Suggestions offered were:

team, admin, support, help, uniswap, sushiswap, pancakeswap, assistant, dev

This would be implemented on the `guildMemberAdd` event. New member joins, the autoban feature runs, and if the user remains afterward, then they get to stay 😂

**Comment by amaredeus** [comment]
Can this be closed now that we have #149 ?

**Comment by nonsensecodes** [comment]
> Can this be closed now that we have #149 ?

Yes. Let’s shut this down 🔥
