### ISSUE TITLE
Develop a Working Cache to Prevent DEGEN from Getting Rate-Limited

### ISSUE THREAD

**Issue by nonsensecodes** [BanklessDAO/discord-bots#58]
While the Discord API carries a global rate limit of 50 requests per second for bots, the discord.js library helps manage rate-limiting with their integration of their `Collections` data structure and custom caches. However, services like Heroku and Notion carry their own API rate limits--[Heroku](https://devcenter.heroku.com/articles/limits#heroku-api-limits) and [Notion](https://developers.notion.com/reference/errors#rate-limits), respectively--and the Notion SDK currently does not contain methods to prevent hitting the Notion API rate limit. Therefore, this issue is being raised to develop an internal cache to manage requests to the Notion API, to allow for uninhibited use of DEGEN's services and execute on commands that are called, no matter the frequency.

**Comment by austinmitchem** [comment]
#74 added p-queue to manage rate limiting to Notion

**Comment by nonsensecodes** [comment]
Closing this issue as it is now complete.
