### ISSUE TITLE
Replace POAP-bot--Season 1 Initiative: Setup Events and Claim Badges

### ISSUE THREAD

**Issue by nonsensecodes** [BanklessDAO/discord-bots#70]
POAP distribution and claiming is challenging with the current implementation of both POAP-bot and POAP-bot-V2 in the Discord server. The purpose of this integration into DEGEN is to provide a more consistent and easy approach to setting up events for distribution and the claiming of POAPs for said events.

**Comment by amaredeus** [comment]
/poap start
/poap end 
/help poap 

is implemented and a good starting point

**Comment by nonsensecodes** [comment]
This is built out and replicable. Closing out this issue; we can open a new one as we discover more use-cases and expand the POAP command.
