### ISSUE TITLE
Replace POAP-bot--Season 2 Initiative: Mint and Collect Claim Links

### ISSUE THREAD

**Issue by nonsensecodes** [BanklessDAO/discord-bots#71]
Currently, the workflow to mint and collect claim links for POAPs requires filling out a webform, replying to a confirmation email, and awaiting the corresponding codes. This issue is being raised to explore the possibility for minting and collecting links directly through DEGEN via poap.xyz's API. Other potential considerations are verifying what wallets hold what badges for purposes of renumeration and guild membership.

**Comment by ZrowGz** [comment]
Additional request submitted to form to add POAP functionality to Guild'd Channel.
Requestor: Mamer#7361
Requesting Team: Analytics Guild
Requested date: 10/31/2021
Bounty offered? TBD - open to discuss
> We'd like to automate the distribution of the guild POAP (to whatever extent possible) for our regular guild meetings

**Comment by nonsensecodes** [comment]
> Additional request submitted to form to add POAP functionality to Guild'd Channel.
> Requestor: Mamer#7361
> Requesting Team: Analytics Guild
> Requested date: 10/31/2021
> Bounty offered? TBD - open to discuss
> 
> > We'd like to automate the distribution of the guild POAP (to whatever extent possible) for our regular guild meetings

This is already live.

**Comment by nonsensecodes** [comment]
Collect and mint feature will be available through the POAP API in 2 to 3 months. We’ll revisit this issue at that time.
