### ISSUE TITLE
User Attendance System (Reduce POAPs)

### ISSUE THREAD

**Issue by amaredeus** [BanklessDAO/discord-bots#85]
Creating and distributing POAPs for all project discussions, meetings, and any internal gatherings in the DAO is very time consuming and can be costly at scale. Proof of attendance is important for the many ideas that the DAO has. To support this it might be better to create a DEGEN attendance system for the various projects and meetings and make use of discord voice API as proof. 

Benefits:
 - reduce POAP clutter
 - reduce cost of having a POAP manager
 - universal Proof of Attendance system within the DAO
 
 Cons:
  - might dissuade members from attending if now they don't get a POAP (are they really in it for the future of the DAO?)

**Comment by nonsensecodes** [comment]
The POAP system for regularly scheduled meetings and events most definitely needs an overhaul. But I don't know if replacing it altogether is the right approach.

The benefit of acquiring a POAP for attending a meeting, joining a project, etc, is that POAPs are blockchain-native, and thus immutable. We can't say the same thing for databases. And while the distribution system currently leaves much to be desired, we do have the opportunity to improve upon it. That is something in the works with DEGEN as well.

I'm personally not married to POAPs for proof of attendance, but the DAO appears to be, as there are initiatives in place to work closely with POAP.xyz to bring wider adoption to the blockchain space in general. If we were to supplant POAPs entirely, there may be other factors at play that could be potentially harmful for the DAO at large.

This is definitely something we will want to discuss DAO-wide. I recommend making a formal proposal on the DAO's Discourse, and driving engagement behind it. While the DAO is discussing it, we can have two different approaches to how we want to measure attendance:

1. Build a better POAP distribution system within DEGEN, that we can then make available as SaaS, so the work isn't wasted if we end going in a different direction, and
2. Discuss a better solution, preferably one that is blockchain-native and not mutable.

We have time to consider this. Obviously, the sooner we come to consensus, the sooner we can direct our energy accordingly and implement what we build, but we'll need to establish that consensus first.

Let's get the conversation started.

**Comment by amaredeus** [comment]
A POAP tracking feature is now implemented as part of #109. Currently it supports Community Call events and Dev Guild discussions

**Comment by amaredeus** [comment]
This is now out in production, will be interesting to see this used throughout the week

**Comment by amaredeus** [comment]
Closing as this has been working great in production
