### ISSUE TITLE
DiscordJS v13 Upgrade

### ISSUE THREAD

**Issue by amaredeus** [BanklessDAO/discord-bots#98]
Fix and addresses all breaking changes between DiscordJS v12 -> DiscordJS v13 https://discordjs.guide/additional-info/changes-in-v13.html#before-you-start

**Comment by nonsensecodes** [comment]
Thank you for opening this, @amaredeus. We’ll be speaking on this at the meeting; this is a good place to carry the convo over to afterwards. Everything that will be under discussion can be found here:
[DEGEN Mechanics Sync](https://www.notion.so/bankless/DEGEN-Mechanics-Sync-1b2988072bcb4c7a823af5e6970619aa)

**Comment by nonsensecodes** [comment]
Codebase update to discord.js v13 is complete! Thank you, @amaredeus. Closing this issue.
